<style type="text/css">
.cc_bar_head {
  padding: 3px 15px;
  margin-top: 18px;
  margin-bottom: 7px;
  width: 85%;
}
</style>

<div class="wrap">
  <h2>Cart66 Cloud Members Settings</h2>

  <h2 class="nav-tab-wrapper">  
    <a href="?page=cart66_members&tab=notifications" class="nav-tab <?php echo $notifications_tab; ?>"><?php _e('Notifications', 'cart66') ?></a>  
    <a href="?page=cart66_members&tab=category-restrictions" class="nav-tab <?php echo $restrict_categories_tab; ?>"><?php _e('Category Restriction', 'cart66') ?></a>  
  </h2> 

  <form action="options.php" method="post">
    <?php 
      if($notifications_tab) {
        settings_fields('ccm_access_notifications'); 
        do_settings_sections('ccm_access_notifications');
      }
      elseif($restrict_categories_tab) {
        settings_fields('ccm_category_restrictions'); 
        do_settings_sections('ccm_category_restrictions');
      }
      submit_button(__('Save Settings'), 'cart66');
    ?>
  </form>

</div>
