<script>
function CS_insert_product_shortcode(){
  var product_id = jQuery('#product_id').val();
  var display_type = jQuery("#display_type").val();
  var display_quantity = jQuery("#display_quantity").is(":checked") ? 'true' : 'false';
  var display_price = jQuery("#display_price").is(":checked") ? 'true' : 'false';
  if(product_id == "0" || product_id == ""){
    alert("<?php _e("Please select a product", "cloudswipe") ?>");
    return;
  }
  window.send_to_editor("[cs_product sku=\"" + product_id + "\" display=\"" + display_type + "\" quantity=\"" + display_quantity + "\" price=\"" + display_price + "\"]");
}
</script>

<style type="text/css">
  #cloudswipe_pop_up .form-table tbody tr th {
    text-align: right;
    width: 150px !important;
  }

  #cloudswipe_pop_up .form-table .description {
    width: 312px;
  }
</style>

<div id="cs_editor_pop_up" style="display:none;">
  <div id="cloudswipe_pop_up" class="wrap">
    <div>
      <div style="padding:15px 15px 0 15px;">
        <h3 style="color:#5A5A5A!important; font-family:Georgia,Times New Roman,Times,serif!important; font-size:1.8em!important; font-weight:normal!important;"><?php _e("Insert A Product", "cloudswipe"); ?></h3>
        <span><?php _e("Select a product below to add it to your post or page.", "cloudswipe"); ?></span>
      </div>
      
      <div style="padding:15px 15px 0 15px;">
        <table class="form-table">
          <tbody>
            <tr valign="top">
              <th scope="row"><label for="product_id">Products</label></th>
              <td>
                <select name="product_id" id="product_id">
                  <?php foreach($product_data as $p): ?>
                    <option value="<?php echo $p['sku']; ?>"><?php echo $p['name']; ?></option>
                  <?php endforeach; ?>
                </select>
              </td>
            </tr>
            <tr valign="top">
              <th scope="row"><label for="display_type">Display mode</label></th>
              <td>
                <select name="display_type" id="display_type">
                  <option value="inline">inline</option>
                  <option value="vertical">vertical</option>
                  <option value="horizontal">horizontal</option>
                </select>
                <p class="description"><?php _e('If the product has no options, we recommend choosing the "inline" display mode.', 'cloudswipe'); ?></p>
              </td>
            </tr>
            <tr valign="top">
              <th scope="row"><label for="display_type">Show quantity field</label></th>
              <td>
                <input type="checkbox" id="display_quantity" checked='checked' /> <label for="display_quantity"><?php _e("Yes", "cloudswipe"); ?></label> &nbsp;&nbsp;&nbsp;
                <p class="description"><?php _e('Allow the buyer to set the quanity when adding to cart', 'cloudswipe'); ?></p>
              </td>
            </tr>
            <tr valign="top">
              <th scope="row"><label for="display_type">Show product price</label></th>
              <td>
                <input type="checkbox" id="display_price" checked='checked' /> <label for="display_price"><?php _e("Yes", "cloudswipe"); ?></label> &nbsp;&nbsp;&nbsp;
                <p class="description"><?php _e('Do you want to show the price of the product?', 'cloudswipe'); ?></p>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      
      <div style="padding:15px;">
        <input type="button" class="button-primary" value="Insert Product" onclick="CS_insert_product_shortcode();"/>&nbsp;&nbsp;&nbsp;
        <a class="button" style="color:#bbb;" href="#" onclick="tb_remove(); return false;"><?php _e("Cancel", "cloudswipe"); ?></a>
      </div>
    </div>
  </div>
</div>
